on:
  push:
    tags:
      - v*

jobs:
  publish-vsce:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x

    - run: npm install

    - name: replace README.md
      run: |
        rm README.md
        mv readmes/vscode.md README.md 

    - name: Publish to Open VSX Registry --pre-release
      if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '-')
      run: ./node_modules/.bin/ovsx publish --pre-release -p "$OPEN_VSX_TOKEN"
      env:
        OPEN_VSX_TOKEN: ${{ secrets.OPEN_VSX_TOKEN }}

    - name: Publish to Open VSX Registry
      if: startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-')
      run: ./node_modules/.bin/ovsx publish -p "$OPEN_VSX_TOKEN"
      env:
        OPEN_VSX_TOKEN: ${{ secrets.OPEN_VSX_TOKEN }}

    - name: set publisher to magicstack
      run: |
        sed -i 's/"publisher": "gel",/"publisher": "magicstack",/' package.json

    - name: Publish to Azure Marketplace --pre-release
      if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '-')
      run: ./node_modules/.bin/vsce publish --pre-release
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}

    - name: Publish to Azure Marketplace
      if: startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-')
      run: ./node_modules/.bin/vsce publish
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
